version: '2'
services:
  web:
    environment:
      - DEBUG
      - POSTGRES_USER=admin
      - POSTGRES_DB=maps
      - POSTGRES_PASSWORD=admin123
      - PG_ADDRESS=172.21.0.2
      - PG_PORT=5432
    build: ./web
    volumes:
      - .:/code
      # - web_data:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    command: python web/manage.py runserver 0.0.0.0:8000

  db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=maps
      - POSTGRES_PASSWORD=admin123
      - PG_ADDRESS=172.21.0.2
      - PG_PORT=5432
    build: ./db
    ports:
      - "5445:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"

  geoserver:
    build: ./geoserver
    ports:
      - "8008:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  nginx:
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - web

volumes:
  db_data:
    driver: local
  web_data:
    driver: local
  geoserver_data:
    driver: local
